"""Curated Wikipedia titles for Phase 1 static knowledge."""

from __future__ import annotations

from typing import TypedDict


class WikiSource(TypedDict):
    title: str
    category: str
    wiki_title: str


WIKIPEDIA_SOURCES: list[WikiSource] = [
    # rules
    {'title': 'Rules of golf', 'category': 'rules', 'wiki_title': 'Rules of golf'},
    {'title': 'Golf', 'category': 'rules', 'wiki_title': 'Golf'},
    {'title': 'Stroke play', 'category': 'rules', 'wiki_title': 'Stroke play'},
    {'title': 'Match play', 'category': 'rules', 'wiki_title': 'Match play'},
    {'title': 'Handicap (golf)', 'category': 'rules', 'wiki_title': 'Handicap (golf)'},
    {'title': 'World Handicap System', 'category': 'rules', 'wiki_title': 'World Handicap System'},
    {'title': 'Stableford', 'category': 'rules', 'wiki_title': 'Stableford'},
    {'title': 'Etiquette in golf', 'category': 'rules', 'wiki_title': 'Etiquette in golf'},
    {'title': 'Golf course', 'category': 'rules', 'wiki_title': 'Golf course'},
    {'title': 'Tee (golf)', 'category': 'rules', 'wiki_title': 'Tee (golf)'},
    {'title': 'Penalty (golf)', 'category': 'rules', 'wiki_title': 'Penalty (golf)'},
    # governing bodies
    {'title': 'The R&A', 'category': 'governing_bodies', 'wiki_title': 'The R&A'},
    {'title': 'United States Golf Association', 'category': 'governing_bodies', 'wiki_title': 'United States Golf Association'},
    {'title': 'PGA of America', 'category': 'governing_bodies', 'wiki_title': 'PGA of America'},
    {'title': 'PGA Tour', 'category': 'governing_bodies', 'wiki_title': 'PGA Tour'},
    {'title': 'LPGA', 'category': 'governing_bodies', 'wiki_title': 'LPGA'},
    {'title': 'International Golf Federation', 'category': 'governing_bodies', 'wiki_title': 'International Golf Federation'},
    {'title': 'DP World Tour', 'category': 'governing_bodies', 'wiki_title': 'DP World Tour'},
    {'title': 'LIV Golf', 'category': 'governing_bodies', 'wiki_title': 'LIV Golf'},
    {'title': 'Ladies European Tour', 'category': 'governing_bodies', 'wiki_title': 'Ladies European Tour'},
    {'title': 'PGA Tour Champions', 'category': 'governing_bodies', 'wiki_title': 'PGA Tour Champions'},
    {'title': 'Korn Ferry Tour', 'category': 'governing_bodies', 'wiki_title': 'Korn Ferry Tour'},
    {'title': 'Royal and Ancient Golf Club of St Andrews', 'category': 'governing_bodies', 'wiki_title': 'Royal and Ancient Golf Club of St Andrews'},
    # history
    {'title': 'History of golf', 'category': 'history', 'wiki_title': 'History of golf'},
    {'title': 'Old Course at St Andrews', 'category': 'history', 'wiki_title': 'Old Course at St Andrews'},
    {'title': 'St Andrews Links', 'category': 'history', 'wiki_title': 'St Andrews Links'},
    {'title': 'Golf in Scotland', 'category': 'history', 'wiki_title': 'Golf in Scotland'},
    {'title': 'Bobby Jones (golfer)', 'category': 'history', 'wiki_title': 'Bobby Jones (golfer)'},
    {'title': 'Francis Ouimet', 'category': 'history', 'wiki_title': 'Francis Ouimet'},
    {'title': 'Augusta National Golf Club', 'category': 'history', 'wiki_title': 'Augusta National Golf Club'},
    # courses
    {'title': 'Pebble Beach Golf Links', 'category': 'courses', 'wiki_title': 'Pebble Beach Golf Links'},
    {'title': 'Pine Valley Golf Club', 'category': 'courses', 'wiki_title': 'Pine Valley Golf Club'},
    {'title': 'Cypress Point Club', 'category': 'courses', 'wiki_title': 'Cypress Point Club'},
    {'title': 'TPC Sawgrass', 'category': 'courses', 'wiki_title': 'TPC Sawgrass'},
    {'title': 'Royal Melbourne Golf Club', 'category': 'courses', 'wiki_title': 'Royal Melbourne Golf Club'},
    {'title': 'Muirfield', 'category': 'courses', 'wiki_title': 'Muirfield'},
    {'title': 'Carnoustie Golf Links', 'category': 'courses', 'wiki_title': 'Carnoustie Golf Links'},
    {'title': 'Royal County Down Golf Club', 'category': 'courses', 'wiki_title': 'Royal County Down Golf Club'},
    {'title': 'Shinnecock Hills Golf Club', 'category': 'courses', 'wiki_title': 'Shinnecock Hills Golf Club'},
    {'title': 'Oakmont Country Club', 'category': 'courses', 'wiki_title': 'Oakmont Country Club'},
    {'title': 'Winged Foot Golf Club', 'category': 'courses', 'wiki_title': 'Winged Foot Golf Club'},
    {'title': 'Valderrama Golf Club', 'category': 'courses', 'wiki_title': 'Valderrama Golf Club'},
    {'title': 'Whistling Straits', 'category': 'courses', 'wiki_title': 'Whistling Straits'},
    {'title': 'Royal Troon Golf Club', 'category': 'courses', 'wiki_title': 'Royal Troon Golf Club'},
    {'title': 'Pinehurst Resort', 'category': 'courses', 'wiki_title': 'Pinehurst Resort'},
    {'title': 'Bethpage Black Course', 'category': 'courses', 'wiki_title': 'Bethpage Black Course'},
    {'title': 'Merion Golf Club', 'category': 'courses', 'wiki_title': 'Merion Golf Club'},
    {'title': 'Royal Portrush Golf Club', 'category': 'courses', 'wiki_title': 'Royal Portrush Golf Club'},
    {'title': 'Bandon Dunes Golf Resort', 'category': 'courses', 'wiki_title': 'Bandon Dunes Golf Resort'},
    # tournaments
    {'title': 'Masters Tournament', 'category': 'tournaments', 'wiki_title': 'Masters Tournament'},
    {'title': 'The Open Championship', 'category': 'tournaments', 'wiki_title': 'The Open Championship'},
    {'title': 'U.S. Open (golf)', 'category': 'tournaments', 'wiki_title': 'U.S. Open (golf)'},
    {'title': 'PGA Championship', 'category': 'tournaments', 'wiki_title': 'PGA Championship'},
    {'title': "Women's major golf championships", 'category': 'tournaments', 'wiki_title': "Women's major golf championships"},
    {'title': 'Chevron Championship', 'category': 'tournaments', 'wiki_title': 'Chevron Championship'},
    {'title': "Women's PGA Championship", 'category': 'tournaments', 'wiki_title': "Women's PGA Championship"},
    {'title': "U.S. Women's Open", 'category': 'tournaments', 'wiki_title': "U.S. Women's Open"},
    {'title': "Women's British Open", 'category': 'tournaments', 'wiki_title': "Women's British Open"},
    {'title': 'The Evian Championship', 'category': 'tournaments', 'wiki_title': 'The Evian Championship'},
    {'title': 'Ryder Cup', 'category': 'tournaments', 'wiki_title': 'Ryder Cup'},
    {'title': 'Presidents Cup', 'category': 'tournaments', 'wiki_title': 'Presidents Cup'},
    {'title': 'Solheim Cup', 'category': 'tournaments', 'wiki_title': 'Solheim Cup'},
    {'title': 'The Players Championship', 'category': 'tournaments', 'wiki_title': 'The Players Championship'},
    {'title': 'FedEx Cup', 'category': 'tournaments', 'wiki_title': 'FedEx Cup'},
    {'title': 'Golf at the Summer Olympics', 'category': 'tournaments', 'wiki_title': 'Golf at the Summer Olympics'},
    {'title': "Walker Cup", 'category': 'tournaments', 'wiki_title': 'Walker Cup'},
    {'title': 'Curtis Cup', 'category': 'tournaments', 'wiki_title': 'Curtis Cup'},
    # players — legends
    {'title': 'Jack Nicklaus', 'category': 'players', 'wiki_title': 'Jack Nicklaus'},
    {'title': 'Tiger Woods', 'category': 'players', 'wiki_title': 'Tiger Woods'},
    {'title': 'Arnold Palmer', 'category': 'players', 'wiki_title': 'Arnold Palmer'},
    {'title': 'Ben Hogan', 'category': 'players', 'wiki_title': 'Ben Hogan'},
    {'title': 'Gary Player', 'category': 'players', 'wiki_title': 'Gary Player'},
    {'title': 'Sam Snead', 'category': 'players', 'wiki_title': 'Sam Snead'},
    {'title': 'Seve Ballesteros', 'category': 'players', 'wiki_title': 'Seve Ballesteros'},
    {'title': 'Nick Faldo', 'category': 'players', 'wiki_title': 'Nick Faldo'},
    {'title': 'Greg Norman', 'category': 'players', 'wiki_title': 'Greg Norman'},
    {'title': 'Annika Sörenstam', 'category': 'players', 'wiki_title': 'Annika Sörenstam'},
    {'title': 'Babe Didrikson Zaharias', 'category': 'players', 'wiki_title': 'Babe Didrikson Zaharias'},
    {'title': 'Mickey Wright', 'category': 'players', 'wiki_title': 'Mickey Wright'},
    {'title': 'Kathy Whitworth', 'category': 'players', 'wiki_title': 'Kathy Whitworth'},
    {'title': 'Patty Berg', 'category': 'players', 'wiki_title': 'Patty Berg'},
    {'title': 'Nancy Lopez', 'category': 'players', 'wiki_title': 'Nancy Lopez'},
    {'title': 'Lorena Ochoa', 'category': 'players', 'wiki_title': 'Lorena Ochoa'},
    {'title': 'Inbee Park', 'category': 'players', 'wiki_title': 'Inbee Park'},
    # players — current
    {'title': 'Scottie Scheffler', 'category': 'players', 'wiki_title': 'Scottie Scheffler'},
    {'title': 'Rory McIlroy', 'category': 'players', 'wiki_title': 'Rory McIlroy'},
    {'title': 'Jon Rahm', 'category': 'players', 'wiki_title': 'Jon Rahm'},
    {'title': 'Xander Schauffele', 'category': 'players', 'wiki_title': 'Xander Schauffele'},
    {'title': 'Collin Morikawa', 'category': 'players', 'wiki_title': 'Collin Morikawa'},
    {'title': 'Viktor Hovland', 'category': 'players', 'wiki_title': 'Viktor Hovland'},
    {'title': 'Justin Thomas', 'category': 'players', 'wiki_title': 'Justin Thomas'},
    {'title': 'Brooks Koepka', 'category': 'players', 'wiki_title': 'Brooks Koepka'},
    {'title': 'Jordan Spieth', 'category': 'players', 'wiki_title': 'Jordan Spieth'},
    {'title': 'Phil Mickelson', 'category': 'players', 'wiki_title': 'Phil Mickelson'},
    {'title': 'Hideki Matsuyama', 'category': 'players', 'wiki_title': 'Hideki Matsuyama'},
    {'title': 'Bryson DeChambeau', 'category': 'players', 'wiki_title': 'Bryson DeChambeau'},
    {'title': 'Patrick Cantlay', 'category': 'players', 'wiki_title': 'Patrick Cantlay'},
    {'title': 'Tommy Fleetwood', 'category': 'players', 'wiki_title': 'Tommy Fleetwood'},
    {'title': 'Shane Lowry', 'category': 'players', 'wiki_title': 'Shane Lowry'},
    {'title': 'Nelly Korda', 'category': 'players', 'wiki_title': 'Nelly Korda'},
    {'title': 'Lydia Ko', 'category': 'players', 'wiki_title': 'Lydia Ko'},
    {'title': 'Charley Hull', 'category': 'players', 'wiki_title': 'Charley Hull'},
    {'title': 'Jin Young Ko', 'category': 'players', 'wiki_title': 'Jin Young Ko'},
    {'title': 'Céline Boutier', 'category': 'players', 'wiki_title': 'Céline Boutier'},
    {'title': 'Lexi Thompson', 'category': 'players', 'wiki_title': 'Lexi Thompson'},
    # players — emerging / young talent
    {'title': 'Ludvig Åberg', 'category': 'players', 'wiki_title': 'Ludvig Åberg'},
    {'title': 'Nick Dunlap', 'category': 'players', 'wiki_title': 'Nick Dunlap'},
    {'title': 'Akshay Bhatia', 'category': 'players', 'wiki_title': 'Akshay Bhatia'},
    {'title': 'Tom Kim', 'category': 'players', 'wiki_title': 'Tom Kim (golfer)'},
    {'title': 'Min Woo Lee', 'category': 'players', 'wiki_title': 'Min Woo Lee'},
    {'title': 'Rose Zhang', 'category': 'players', 'wiki_title': 'Rose Zhang'},
    {'title': 'Sahith Theegala', 'category': 'players', 'wiki_title': 'Sahith Theegala'},
    {'title': 'Wyndham Clark', 'category': 'players', 'wiki_title': 'Wyndham Clark'},
    {'title': 'Joaquín Niemann', 'category': 'players', 'wiki_title': 'Joaquín Niemann'},
    {'title': 'Keegan Bradley', 'category': 'players', 'wiki_title': 'Keegan Bradley'},
    {'title': 'Cameron Smith (golfer)', 'category': 'players', 'wiki_title': 'Cameron Smith (golfer)'},
    {'title': 'Rickie Fowler', 'category': 'players', 'wiki_title': 'Rickie Fowler'},
    {'title': 'Lottie Woad', 'category': 'players', 'wiki_title': 'Lottie Woad'},
    {'title': 'Jackson Koivun', 'category': 'players', 'wiki_title': 'Jackson Koivun'},
    {'title': 'Gordon Sargent', 'category': 'players', 'wiki_title': 'Gordon Sargent'},
    {'title': 'Miles Russell (golfer)', 'category': 'players', 'wiki_title': 'Miles Russell (golfer)'},
    # glossary / terminology
    {'title': 'Glossary of golf', 'category': 'glossary', 'wiki_title': 'Glossary of golf'},
    {'title': 'Caddie', 'category': 'glossary', 'wiki_title': 'Caddie'},
    {'title': 'Fore (golf)', 'category': 'glossary', 'wiki_title': 'Fore (golf)'},
    {'title': 'Mulligan (golf)', 'category': 'glossary', 'wiki_title': 'Mulligan (golf)'},
    {'title': 'Par (score)', 'category': 'glossary', 'wiki_title': 'Par (score)'},
    {'title': 'Bogey (golf)', 'category': 'glossary', 'wiki_title': 'Bogey (golf)'},
    {'title': 'Scratch golfer', 'category': 'glossary', 'wiki_title': 'Scratch golfer'},
    {'title': 'Albatross (golf)', 'category': 'glossary', 'wiki_title': 'Albatross (golf)'},
    {'title': 'Condor (golf)', 'category': 'glossary', 'wiki_title': 'Condor (golf)'},
    {'title': 'Hole in one', 'category': 'glossary', 'wiki_title': 'Hole in one'},
    {'title': 'Stymie (golf)', 'category': 'glossary', 'wiki_title': 'Stymie (golf)'},
    {'title': 'Dormie', 'category': 'glossary', 'wiki_title': 'Dormie'},
    {'title': 'Shamble (golf)', 'category': 'glossary', 'wiki_title': 'Shamble (golf)'},
    {'title': 'Scramble (golf)', 'category': 'glossary', 'wiki_title': 'Scramble (golf)'},
    {'title': 'Best ball', 'category': 'glossary', 'wiki_title': 'Best ball'},
    {'title': 'Fourball', 'category': 'glossary', 'wiki_title': 'Four-ball golf'},
    {'title': 'Foursome (golf)', 'category': 'glossary', 'wiki_title': 'Foursome (golf)'},
    {'title': 'Links (golf)', 'category': 'glossary', 'wiki_title': 'Links (golf)'},
    {'title': 'Rough (golf)', 'category': 'glossary', 'wiki_title': 'Rough (golf)'},
    {'title': 'Bunker (golf)', 'category': 'glossary', 'wiki_title': 'Bunker (golf)'},
    {'title': 'Green (golf)', 'category': 'glossary', 'wiki_title': 'Green (golf)'},
    # 'Fairway' alone is a disambiguation page; this redirects to Golf course § Fairway.
    {'title': 'Fairway', 'category': 'glossary', 'wiki_title': 'Fairway (golf)'},
    # equipment
    {'title': 'Golf club', 'category': 'equipment', 'wiki_title': 'Golf club'},
    {'title': 'Golf ball', 'category': 'equipment', 'wiki_title': 'Golf ball'},
    {'title': 'Wood (golf)', 'category': 'equipment', 'wiki_title': 'Wood (golf)'},
    {'title': 'Iron (golf)', 'category': 'equipment', 'wiki_title': 'Iron (golf)'},
    {'title': 'Wedge (golf)', 'category': 'equipment', 'wiki_title': 'Wedge (golf)'},
    {'title': 'Putter', 'category': 'equipment', 'wiki_title': 'Putter'},
    {'title': 'Golf bag', 'category': 'equipment', 'wiki_title': 'Golf bag'},
    {'title': 'Golf cart', 'category': 'equipment', 'wiki_title': 'Golf cart'},
    {'title': 'Teeing ground', 'category': 'equipment', 'wiki_title': 'Teeing ground'},
    # foundations / charities
    {'title': 'The First Tee', 'category': 'foundations', 'wiki_title': 'The First Tee'},
    {'title': 'TGR Foundation', 'category': 'foundations', 'wiki_title': 'TGR Foundation'},
    {'title': 'Evans Scholars Foundation', 'category': 'foundations', 'wiki_title': 'Evans Scholars Foundation'},
    {'title': 'Arnold Palmer Hospital for Children', 'category': 'foundations', 'wiki_title': 'Arnold Palmer Hospital for Children'},
    {'title': 'Make-A-Wish Foundation', 'category': 'foundations', 'wiki_title': 'Make-A-Wish Foundation'},
]
